# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Publish

on:
   push: {tags:  ['v*'] }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: cd TokimekiTools && dotnet publish -p:PublishProfile=FolderProfile
    - name: 7zip release
      run : 7z a -t7z -mx=9 TokimekiTools_win-x64_release.7z ./TokimekiTools/publish/
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "TokimekiTools_win-x64_release.7z"
        bodyFile: ""
        token: ${{ secrets.GITHUB_TOKEN }}
